# Generated by Django 5.1.3 on 2024-11-19 07:40

from django.db import migrations

sizes = [
    {'name': 'small', 'symbol': 'S'},
    {'name': 'medium', 'symbol': 'M'},
    {'name': 'large', 'symbol': 'L'},
    {'name': 'extralarge', 'symbol': 'XL'},
]

def populate_size(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Size = apps.get_model("grandraid", "Size")

    for size in sizes:
        new_size = Size(**size)
        new_size.save()

def depopulate_size(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Size = apps.get_model("grandraid", "Size")

    for size in Size.objects.all():
        size.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('grandraid', '0002_course_runnercategory_size'),
    ]

    operations = [
        migrations.RunPython(populate_size, depopulate_size)
    ]
