# Generated by Django 5.1.3 on 2024-11-19 09:08

from django.db import migrations

runnercategories = [
    {'start_year': 1940, 'end_year': 1949, 'category': 'V4'},
    {'start_year': 1950, 'end_year': 1959, 'category': 'V3'},
    {'start_year': 1960, 'end_year': 1969, 'category': 'V2'},
    {'start_year': 1970, 'end_year': 1979, 'category': 'V1'},
    {'start_year': 1980, 'end_year': 1996, 'category': 'SE'},
    {'start_year': 1997, 'end_year': 1999, 'category': 'ES'},
    {'start_year': 2000, 'end_year': 2001, 'category': 'JU'},
    {'start_year': 2002, 'end_year': 2003, 'category': 'CA'},
    {'start_year': 2004, 'end_year': 2005, 'category': 'MI'},
]

def populate_runnercategories(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    RunnerCategory = apps.get_model("grandraid", "RunnerCategory")

    for category in runnercategories:
        new_category = RunnerCategory(**category)
        new_category.save()

def depopulate_runnercategories(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    RunnerCategory = apps.get_model("grandraid", "RunnerCategory")

    for category in RunnerCategory.objects.all():
        category.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('grandraid', '0003_auto_20241119_0740'),
    ]

    operations = [
        migrations.RunPython(populate_runnercategories, depopulate_runnercategories)
    ]
