# Generated by Django 5.1.3 on 2024-11-19 10:01

from django.db import migrations

meals= [
    {"type": "before", "prix": 8},
    {"type": "after", "prix": 10},

]

def populate_meals(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Meal = apps.get_model("grandraid", "Meal")

    for meal in meals:
        new_meal = Meal(**meal)
        new_meal.save()

def depopulate_meals(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Meal = apps.get_model("grandraid", "Meal")

    for meal in Meal.objects.all():
        meal.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('grandraid', '0006_meal_runner_delete_repas_alter_club_city_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_meals, depopulate_meals)
    ]
