# Generated by Django 5.1.3 on 2024-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandraid', '0009_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='yo'),
            preserve_default=False,
        ),
    ]
