# Generated by Django 5.1.3 on 2024-11-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandraid', '0010_meal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='category',
        ),
    ]
