# Generated by Django 5.1.3 on 2024-12-16

from django.db import migrations

def update_meal_names(apps, schema_editor):
    # Récupère le modèle Meal
    Meal = apps.get_model("grandraid", "Meal")

    # Mise à jour des noms des repas
    Meal.objects.filter(type="before").update(name="Repas avant")
    Meal.objects.filter(type="after").update(name="Repas après")

def revert_meal_names(apps, schema_editor):
    # Récupère le modèle Meal
    Meal = apps.get_model("grandraid", "Meal")

    # Supprime les noms mis à jour (revenir à une valeur par défaut vide ou à autre chose)
    Meal.objects.filter(type="before").update(name="")
    Meal.objects.filter(type="after").update(name="")

class Migration(migrations.Migration):

    dependencies = [
        ('grandraid', '0010_meal_name'),  # Assurez-vous que ce numéro de migration est correct
    ]

    operations = [
        migrations.RunPython(update_meal_names, revert_meal_names),
    ]