# Generated by Django 4.2.17 on 2024-12-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandraid', '0011_remove_runner_category'),
        ('grandraid', '0012_auto_20241216_0745'),
    ]

    operations = [
    ]
