# Generated by Django 5.1.3 on 2024-12-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='value_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
