# Generated by Django 5.1.3 on 2024-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesbases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
