# Generated by Django 5.1.3 on 2024-12-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grossiste', models.BooleanField(default=False)),
                ('paiement_comptant', models.BooleanField(default=False)),
                ('vente_emportee', models.BooleanField(default=False)),
                ('marchandise_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remise_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sous_total_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sous_total_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('escompte', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_de_port', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
