# Generated by Django 5.1.3 on 2024-12-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='num_facture',
            field=models.CharField(default='inv-xxx', max_length=50),
        ),
    ]
